version: '3.8'

services:
  redis:
    image: redis:7.0.4
    ports:
      - "6379:6379"

  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:14.5
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
      
volumes:
  postgres_data:
