# Generated by Django 5.1.1 on 2024-10-01 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_books_book_id_ffa80d_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='book',
            name='books_book_id_ffa80d_idx',
        ),
    ]
